FROM php:8.1-apache

WORKDIR /var/www/html

# Development dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y \
  git \
  zip \
  curl \
  sudo \
  unzip \
  libicu-dev \
  libbz2-dev \
  libpng-dev \
  libjpeg-dev \
  libmcrypt-dev \
  libreadline-dev \
  libfreetype6-dev \
  libwebp-dev \
  libxpm-dev \
  libsodium-dev \
  zlib1g-dev \
  libonig-dev \
  g++

# Install Dependencies
RUN docker-php-ext-install \
    bz2 \
    iconv \
    bcmath \
    opcache \
    calendar \
    mbstring

# Install gd
RUN docker-php-ext-configure gd \
  --enable-gd \
  --with-webp \
  --with-jpeg \
  --with-xpm \
  --with-freetype \
  --enable-gd-jis-conv \
  && docker-php-ext-install -j$(nproc) gd \
  && true

# Install intl
RUN docker-php-ext-configure intl \
  && docker-php-ext-install intl \
  && true

# Install mysqli
RUN docker-php-ext-install mysqli \
  && true 

# Install pdo_mysql
RUN docker-php-ext-configure pdo_mysql --with-zlib-dir=/usr/include/ \
  && docker-php-ext-install pdo_mysql \
  && true

# Install pcntl(for horizon)
RUN docker-php-ext-install pcntl \
    && true

COPY --from=composer:2.0.2 /usr/bin/composer /usr/local/bin/composer

# Install the Oracle Instant Client
ADD server/oracle_client/instantclient-basiclite-linux.x64-19.14.0.0.0dbru.zip /tmp
ADD server/oracle_client/instantclient-sdk-linux.x64-19.14.0.0.0dbru.zip /tmp

RUN apt-get update && apt-get -y install libaio1 \
  && unzip /tmp/instantclient-basiclite-linux.x64-19.14.0.0.0dbru.zip -d /usr/local/ \
  && unzip /tmp/instantclient-sdk-linux.x64-19.14.0.0.0dbru.zip -d /usr/local/ \
  && mv /usr/local/instantclient_19_14 /usr/local/instantclient \
  && ln -sf /usr/local/instantclient/libclntsh.so.19.1 /usr/local/instantclient/libclntsh.so \
  && ln -s /usr/local/instantclient/lib* /usr/lib

RUN echo 'instantclient,/usr/local/instantclient/' | pecl install oci8 \
  && docker-php-ext-enable oci8 \
  && docker-php-ext-configure pdo_oci --with-pdo-oci=instantclient,/usr/local/instantclient \
  && docker-php-ext-install pdo_oci

#RUN echo "extension=oci8.so" >> /usr/local/etc/php/php.ini

RUN a2enmod rewrite
RUN service apache2 restart